### ISSUE TITLE
Advice on combining multiple 10x experiments

### ISSUE THREAD

**Issue by jeremycfd** [urrutiag/destin#2]
Hello,

I've been playing around with destin for analysis of scATACseq matrices produced by CellRanger, which currently does not facilitate aggregation of peaks or counts across multiple data sets. I was wondering if you had any suggestions for doing that within the context of destin analyses, or if you think it would need to happen up-stream of the matrix generation.

Thanks for putting together a great package!

**Comment by yuchaojiang** [comment]
Hi,

I assume that the two datasets from CellRanger have different number of peaks. You can find the shared peaks by overlapping the two GRanges and concatenate the two rse objects accordingly (i.e., remove non-shared peaks and combine shared peaks). If you need help with this, please send sample dataset of ~10 cells each.

One thing I would recommend to be careful about is the potential batch effect from the two 10X runs. Currently we are not dealing with this since the dimension is too large compared to scRNA-seq. Some sanity check can be helpful to determine whether batch effect is prominent and whether clustering should be run separately.

Gene, feel free to fill in or correct me.

**Comment by jeremycfd** [comment]
Thanks for the prompt response. In some cases it makes sense to me to only focus on shared peaks, but in other cases we are interested in comparing samples where we expect extreme differences in which regions are open, but we want to explore those differences in the context of all of the cells from all of the samples. Hrm...

**Comment by yuchaojiang** [comment]
Not sure how much difference in terms of number of peaks you would see between two runs. However, based on what you described, you should resort back to further upstream (e.g., merge the two fastqs although between two runs, yet you get greater chance of two cells sharing the same cellular barcode).
